/* Generated by scripts/gallery-build — do not edit by hand. */
/* Each value is the raw text of the v2 skin's contributed stylesheets
   (skin.css + optional patches.css). The preview simulator injects them
   into the official-facade snapshot; skin JS (hooks.mjs) is never executed. */
window.SKIN_STYLES = {
};
