/**
 * Wallpaper Engine HTTP routes for the skin center — the browser half talks
 * to the host through same-origin endpoints under /api/skin-center/we:
 *
 *   GET  /inventory           → JSON wallpaper list (library + import store)
 *   GET  /media/<token>       → video stream (Range supported)
 *   GET  /preview/<token>     → preview image
 *   GET  /web/<token>/<path>  → web-wallpaper project files (HTML is served
 *                               with the WE API shim injected)
 *   GET  /shim.js             → the WE API shim source (we-shim-source.ts)
 *   GET  /scene-frame/<token> → PNG of a scene wallpaper's main texture,
 *                               decoded in-process (pkg-extract.ts), cached
 *                               under the import store's .cache directory
 *   GET  /image/<token>       → macOS Desktop Pictures: jpg/png/webp served
 *                               directly, HEIC converted to JPEG through
 *                               sips, cached under the import store's
 *                               .cache directory (darwin only)
 *   POST /import              → copy a library wallpaper into the import
 *                               store (<harnessHome>/skin-center/wallpapers)
 *   POST /reimport            → refresh an imported copy from its source
 *   POST /remove              → delete an imported copy
 *
 * Tokens are base64url of an absolute path, issued only by the inventory
 * handler, so a crafted token can never reach a path the library scan did
 * not already expose. Every route rides the skin-center same-origin fence
 * (routes.ts) — wallpaper imports must not be triggerable cross-site. The
 * read-only content routes consumed by the wallpaper iframes themselves
 * (/web/, /shim.js, /scene-manifest/, /scene-resource/) use the relaxed
 * content-origin fence instead: those frames are sandboxed without
 * allow-same-origin, so their own asset loads arrive as Sec-Fetch-Site:
 * cross-site by design.
 *
 * Compliance note: this module only ever reads files already present on the
 * user's machine (their own Wallpaper Engine library) or copies them within
 * it. Nothing is downloaded, uploaded, or redistributed.
 * @module @linxin666/dsh-client-ui-skin-center/we-routes
 */

import { execFile } from 'node:child_process'
import { cpSync, createReadStream, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { readFile, stat } from 'node:fs/promises'
import type { IncomingMessage, ServerResponse } from 'node:http'
import { pipeline, type Readable } from 'node:stream'
import { basename, dirname, extname, join as joinPath, resolve as resolvePath, sep } from 'node:path'
import type { WebRoute } from '@deepseek-ai/dsh-host-webserver'
import { writeJson, readJsonBody, requireContentOrigin, requireSameOrigin } from './http-utils.ts'
import {
  buildInventory,
  inventoryFingerprint,
  locateWallpaperEngine,
  owningLibraries,
  type MacosWallpaperRoots,
  type WallpaperEntry,
  type WallpaperType,
  type WeInventory,
} from './we-library.ts'
import { defaultMacosWallpaperRoots } from './macos-library.ts'
import {
  buildSceneManifest,
  buildSceneManifestFromDir,
  decodeTex,
  encodePng,
  extractSceneResource,
  extractSceneResourceFromDir,
  hasSceneVideo,
  hasSceneVideoFromDir,
  TexUnsupportedError,
} from './pkg-extract.ts'
import { WE_SHIM_JS } from './we-shim-source.ts'
import { WE_SCENE_PLAYER_HTML } from './we-player-source.ts'

/**
 * Scene extraction cache format version, embedded in every frames/videos
 * cache key. The cache keys used to be path + mtime only, so an extraction
 * pipeline change (the #751 projection crop, the #761 TEXI rect crop)
 * never invalidated frames generated by an older build — users who had
 * viewed a wallpaper before the upgrade kept being served the stale frame
 * forever (#792). Bump this whenever the extractor output may change; old
 * cache files then miss, regenerate under the new key, and get pruned.
 */
export const SCENE_EXTRACTOR_VERSION = 2

/**
 * Delete same-wallpaper cache files left by earlier extractor versions or
 * older mtimes, so a version bump does not leave stale debris growing the
 * cache directory forever. The stem comparison is exact: the trailing
 * `[_vN_]<mtime>.<ext>` suffix is stripped first, so one base64url path
 * never prunes another (base64url output can itself contain underscores).
 */
function pruneStaleSceneCache(cacheDir: string, base: string, keep: string): void {
  let entries: string[]
  try { entries = readdirSync(cacheDir) } catch { /* unreadable or absent: nothing to prune */ return }
  for (const name of entries) {
    if (name === keep) continue
    const stem = name.replace(/_(?:v\d+_)?\d+\.[a-z0-9]+$/i, '')
    if (stem === base) {
      try { rmSync(joinPath(cacheDir, name), { force: true }) } catch { /* best effort */ }
    }
  }
}

/**
 * Read a web wallpaper's project.json property defaults so the shim can
 * deliver them like WE does on startup. Values pass through raw: colors stay
 * 'r g b' strings, sliders numbers, checkboxes booleans — exactly what the
 * web API hands to applyUserProperties.
 */
function webPropertyDefaults(projectRoot: string): Record<string, { value: unknown }> {
  const out: Record<string, { value: unknown }> = {}
  try {
    const raw = readFileSync(joinPath(projectRoot, 'project.json'), 'utf8')
    const props = (JSON.parse(raw) as { general?: { properties?: Record<string, { value?: unknown }> } })
      .general?.properties
    if (props) {
      for (const [key, def] of Object.entries(props)) {
        if (def && typeof def === 'object' && 'value' in def) out[key] = { value: def.value }
      }
    }
  } catch { /* no project.json or unreadable: empty defaults */ }
  return out
}

/** Browser-facing base path of the wallpaper API. */
export const WE_API_PREFIX = '/api/skin-center/we'

/** The slice of the skin-wallpaper settings these routes read. */
export interface WeRouteConfig {
  /** Manual library folders (settings field weLibraryDirs). */
  weLibraryDirs?: string[]
}

/** Dependencies the route family needs from the host plugin. */
export interface WeRouteDeps {
  /** Live getter for the skin-wallpaper settings (scope-backed). */
  getConfig: () => WeRouteConfig
  /** Import-store root (<harnessHome>/skin-center/wallpapers). */
  storeDir: string
  /** Auto-detect Steam / Wallpaper Engine installation (default true). */
  autoDetect?: boolean
  /** macOS wallpaper roots override (tests); undefined uses the darwin defaults. */
  macosRoots?: MacosWallpaperRoots | null
  /** Platform override for tests (the macOS scan gates on darwin). */
  platform?: NodeJS.Platform
  /** HEIC converter override for tests (default: sips on darwin). */
  convertImage?: (src: string, dest: string) => Promise<void>
  /** Internal stream factory override used by route-level lifecycle tests. */
  openReadStream?: (path: string, options?: { start?: number; end?: number }) => Readable
}

/** Sanitize a wallpaper id into a safe store directory name. */
export function safeStoreId(id: string): string {
  return id.replace(/[^a-zA-Z0-9._-]/g, '_')
}

/** Minimal mime map for wallpaper payloads. */
function mimeFor(absPath: string): string {
  const ext = extname(absPath).slice(1).toLowerCase()
  return {
    mp4: 'video/mp4', webm: 'video/webm', mkv: 'video/x-matroska',
    avi: 'video/x-msvideo', mov: 'video/quicktime',
    html: 'text/html; charset=utf-8', htm: 'text/html; charset=utf-8',
    js: 'text/javascript; charset=utf-8', mjs: 'text/javascript; charset=utf-8',
    css: 'text/css; charset=utf-8', json: 'application/json; charset=utf-8',
    png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif',
    webp: 'image/webp', svg: 'image/svg+xml', ico: 'image/x-icon',
    mp3: 'audio/mpeg', wav: 'audio/wav', ogg: 'audio/ogg',
    woff: 'font/woff', woff2: 'font/woff2', ttf: 'font/ttf', otf: 'font/otf',
    wasm: 'application/wasm',
  }[ext] || 'application/octet-stream'
}

/** Pipe one file while coupling its descriptor lifetime to the HTTP response. */
function pipeFile(
  absPath: string,
  res: ServerResponse,
  openReadStream: NonNullable<WeRouteDeps['openReadStream']>,
  options?: { start?: number; end?: number },
): void {
  if (res.destroyed || res.writableEnded) return

  const source = openReadStream(absPath, options)
  const closeSource = () => source.destroy()
  res.once('close', closeSource)
  if (res.destroyed || res.writableEnded) {
    res.off('close', closeSource)
    source.destroy()
    return
  }

  try {
    pipeline(source, res, () => {
      res.off('close', closeSource)
      // The callback consumes read and premature-close errors.
    })
  } catch {
    res.off('close', closeSource)
    source.destroy()
  }
}

/** Stream one file with Range support (video seeking needs 206). */
function serveFile(
  absPath: string,
  req: IncomingMessage,
  res: ServerResponse,
  openReadStream: NonNullable<WeRouteDeps['openReadStream']>,
  extraHeaders: Record<string, string> = {},
): void {
  if (!existsSync(absPath) || !statSync(absPath).isFile()) {
    writeJson(res, 404, { ok: false, error: 'not-found' })
    return
  }
  const size = statSync(absPath).size
  res.setHeader('Content-Type', mimeFor(absPath))
  res.setHeader('Accept-Ranges', 'bytes')
  for (const [key, value] of Object.entries(extraHeaders)) res.setHeader(key, value)
  const range = req.headers.range
  if (range) {
    const match = /bytes=(\d*)-(\d*)/.exec(range)
    let start = match && match[1] ? parseInt(match[1], 10) : 0
    let end = match && match[2] ? parseInt(match[2], 10) : size - 1
    if (Number.isNaN(start)) start = 0
    if (Number.isNaN(end) || end >= size) end = size - 1
    if (start > end) {
      res.statusCode = 416
      res.setHeader('Content-Range', 'bytes */' + String(size))
      res.end()
      return
    }
    res.statusCode = 206
    res.setHeader('Content-Range', 'bytes ' + String(start) + '-' + String(end) + '/' + String(size))
    res.setHeader('Content-Length', String(end - start + 1))
    pipeFile(absPath, res, openReadStream, { start, end })
    return
  }
  res.setHeader('Content-Length', String(size))
  pipeFile(absPath, res, openReadStream)
}

/** The JSON shape of one wallpaper entry sent to the browser. */
interface WallpaperJson {
  id: string
  title: string
  type: WallpaperType
  source: WallpaperEntry['source']
  playable: boolean
  updateAvailable: boolean
  videoUrl: string | null
  webUrl: string | null
  frameUrl: string | null
  sceneUrl: string | null
  previewUrl: string | null
}

/** Cached per-scene capability probe result. */
const SCENE_PROBE_VERSION = 4

interface SceneProbe {
  v: number
  hasVideo: boolean
  hasSceneWebGL: boolean
  compatibility: 'full' | 'partial' | 'static-only'
  unsupportedFeatures: string[]
}

/** Shape-check an entry loaded from the persisted probe cache. */
function isSceneProbe(value: unknown): value is SceneProbe {
  return value !== null && typeof value === 'object'
    && (value as SceneProbe).v === SCENE_PROBE_VERSION
    && typeof (value as SceneProbe).hasVideo === 'boolean'
    && typeof (value as SceneProbe).hasSceneWebGL === 'boolean'
    && ((value as SceneProbe).compatibility === 'full' || (value as SceneProbe).compatibility === 'partial' || (value as SceneProbe).compatibility === 'static-only')
    && Array.isArray((value as SceneProbe).unsupportedFeatures)
}

/** Build the route family. */
export function makeWeRoutes(deps: WeRouteDeps): WebRoute[] {
  const openReadStream = deps.openReadStream ?? createReadStream

  // token -> absolute path, issued by the inventory handler only. The map
  // is persisted under the import store cache so issued media URLs survive
  // host restarts without ever accepting a client-supplied path.
  const tokenStorePath = joinPath(deps.storeDir, '.cache', 'we-tokens.json')
  let mediaMap = new Map<string, string>()
  try {
    const saved = JSON.parse(readFileSync(tokenStorePath, 'utf8')) as Record<string, string>
    if (saved !== null && typeof saved === 'object') {
      mediaMap = new Map(Object.entries(saved))
    }
  } catch { /* no store yet: start empty */ }
  const persistTokens = (): void => {
    try {
      mkdirSync(dirname(tokenStorePath), { recursive: true })
      writeFileSync(tokenStorePath, JSON.stringify(Object.fromEntries(mediaMap)), 'utf8')
    } catch { /* best effort; a failed persist only costs token re-issue */ }
  }
  const tokenFor = (absPath: string): string => {
    const token = Buffer.from(absPath, 'utf8').toString('base64url')
    mediaMap.set(token, absPath)
    return token
  }

  // In-process inventory cache (#T2-10): the full library scan (per-project
  // readdir + project.json parse + stats, plus the registry probe under
  // auto-detect) used to run on every inventory / scene-probe / import
  // request. The scan is now cached and re-run only when the fingerprint of
  // everything it reads changes; import / reimport / remove writes
  // invalidate proactively (a write inside the same mtime tick or a brand
  // new entry the previous scan never saw must not be hidden). The reg.exe
  // registry probe is process-memoized in we-library.ts.
  let inventoryCache: { key: string; value: WeInventory } | null = null
  const invalidateInventory = (): void => { inventoryCache = null }
  const freshInventory = (): WeInventory => {
    const manualDirs = deps.getConfig().weLibraryDirs ?? []
    const autoDetect = deps.autoDetect ?? true
    // Detection runs before every fingerprint: a Steam library added or
    // removed mid-session must invalidate the cache, and detection itself
    // only re-runs reg.exe once per process (memoized).
    const installDir = autoDetect ? locateWallpaperEngine() : null
    const libraryDirs = autoDetect ? owningLibraries() : []
    // macOS wallpaper stores (aerials + Desktop Pictures) ride the same
    // auto-detect switch; off-darwin they are empty by construction.
    const macos = deps.macosRoots !== undefined
      ? deps.macosRoots
      : (autoDetect && process.platform === 'darwin' ? defaultMacosWallpaperRoots() : null)
    const key = inventoryFingerprint({
      installDir,
      libraryDirs,
      manualDirs,
      storeDir: deps.storeDir,
      entries: inventoryCache?.value.wallpapers,
      macos,
    })
    if (inventoryCache && inventoryCache.key === key) return inventoryCache.value
    const value = buildInventory({
      manualDirs,
      storeDir: deps.storeDir,
      autoDetect: false,
      installDir,
      libraryDirs,
      macos,
      platform: deps.platform,
    })
    // Store a key computed from the entries this scan produced; the
    // previous entry set described the previous scan and would invalidate
    // the cache on every request.
    inventoryCache = {
      key: inventoryFingerprint({
        installDir,
        libraryDirs,
        manualDirs,
        storeDir: deps.storeDir,
        entries: value.wallpapers,
        macos,
      }),
      value,
    }
    return value
  }

  // hasVideo / hasSceneWebGL probes parse whole pkgs (LZ4 decompress, tex
  // decode), so cache them by path+mtime+size: the probe route would
  // otherwise re-parse the selected scene's whole payload on every request.
  // The cache persists to the import store so a host restart does not
  // re-read a large scene.pkg on the first selection after boot (#817).
  const probeCachePath = joinPath(deps.storeDir, '.cache', 'we-scene-probes.json')
  let sceneProbeCache = new Map<string, SceneProbe>()
  try {
    const saved = JSON.parse(readFileSync(probeCachePath, 'utf8')) as Record<string, unknown>
    if (saved !== null && typeof saved === 'object') {
      for (const [key, value] of Object.entries(saved)) {
        if (isSceneProbe(value)) sceneProbeCache.set(key, value)
      }
    }
  } catch { /* no cache yet: start empty */ }
  const MAX_PROBE_CACHE = 256
  const persistProbes = (): void => {
    try {
      mkdirSync(dirname(probeCachePath), { recursive: true })
      writeFileSync(probeCachePath, JSON.stringify(Object.fromEntries(sceneProbeCache)), 'utf8')
    } catch { /* best effort; a failed persist only costs a re-probe */ }
  }

  const entryToJson = (entry: WallpaperEntry): WallpaperJson => {
    const hasFile = existsSync(entry.fileAbs)
    // macOS Desktop Pictures (HEIC): the browser cannot decode HEIC, so the
    // thumbnail and the mounted backdrop both come from the converting
    // /image route rather than a raw file preview.
    if (entry.type === 'image') {
      return {
        id: entry.id,
        title: entry.title,
        type: entry.type,
        source: entry.source,
        playable: false,
        updateAvailable: false,
        videoUrl: null,
        webUrl: null,
        frameUrl: null,
        sceneUrl: null,
        previewUrl: hasFile ? WE_API_PREFIX + '/image/' + tokenFor(entry.fileAbs) : null,
      }
    }
    // Scene video/WebGL capabilities are probed lazily by the scene-probe
    // route for the selected wallpaper only; probing every scene here would
    // read the whole packed payload of a large library on every inventory.
    return {
      id: entry.id,
      title: entry.title,
      type: entry.type,
      source: entry.source,
      playable: entry.playable,
      updateAvailable: entry.updateAvailable,
      videoUrl: entry.type === 'video' && hasFile ? WE_API_PREFIX + '/media/' + tokenFor(entry.fileAbs) : null,
      webUrl: entry.type === 'web' && hasFile ? WE_API_PREFIX + '/web/' + tokenFor(entry.fileAbs) + '/' : null,
      frameUrl: entry.type === 'scene' && hasFile ? WE_API_PREFIX + '/scene-frame/' + tokenFor(entry.fileAbs) : null,
      sceneUrl: null,
      previewUrl: entry.previewAbs ? WE_API_PREFIX + '/preview/' + tokenFor(entry.previewAbs) : null,
    }
  }

  /**
   * Resolve a token from a prefix route, or answer 404. Tokens resolve
   * through the issued-token map only: a client-supplied path must never
   * reach the filesystem, otherwise any wallpaper (web wallpapers run
   * arbitrary JS same-origin) could read arbitrary local files.
   */
  const resolveToken = (req: IncomingMessage, res: ServerResponse, prefix: string): string | null => {
    let token = ''
    try {
      const pathname = new URL(req.url || '/', 'http://localhost').pathname
      token = decodeURIComponent(pathname.slice(prefix.length).split('/')[0] ?? '')
    } catch { /* malformed escape sequence: no such token */ }
    const abs = mediaMap.get(token)
    if (!abs) {
      writeJson(res, 404, { ok: false, error: 'unknown-token' })
      return null
    }
    return abs
  }

  const routes: WebRoute[] = []

  // GET /inventory — the wallpaper list; also (re)issues all media tokens.
  routes.push({
    kind: 'exact',
    path: WE_API_PREFIX + '/inventory',
    handler: (req, res) => {
      if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      try {
        const inventory = freshInventory()
        const wallpapers = inventory.wallpapers.map(entryToJson)
        persistTokens()
        writeJson(res, 200, {
          ok: true,
          installDir: inventory.installDir,
          total: inventory.total,
          portableCount: inventory.portableCount,
          systemCount: inventory.wallpapers.filter((w) => w.source === 'system').length,
          wallpapers,
        })
      } catch (error) {
        writeJson(res, 500, { ok: false, error: error instanceof Error ? error.message : String(error) })
      }
    },
  })

  // GET /scene-probe?id=<id> — lazy per-item capability probe. Inventory
  // stays cheap by never reading scene payloads; the client asks this route
  // only for the wallpaper the user actually selects. The probe reads the
  // whole packed scene file once (cached by path+mtime+size, persisted to
  // the import store so restarts do not re-read it), and only on a cache
  // miss — a large library is never scanned up front (#817).
  routes.push({
    kind: 'exact',
    path: WE_API_PREFIX + '/scene-probe',
    handler: async (req, res) => {
      if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      try {
        const url = new URL(req.url ?? '', 'http://localhost')
        const id = url.searchParams.get('id')
        if (!id) { writeJson(res, 400, { ok: false, error: 'missing-id' }); return }
        const entry = freshInventory().wallpapers.find((w) => w.id === id && w.type === 'scene')
        if (!entry || !existsSync(entry.fileAbs)) { writeJson(res, 404, { ok: false, error: 'not-found' }); return }
        let mtimeMs = 0
        let size = 0
        try { const st = await stat(entry.fileAbs); mtimeMs = st.mtimeMs; size = st.size } catch { /* probe once without a key */ }
        // Loose .json scenes probe the whole directory (video/manifest
        // siblings), which a single-file stat key cannot fingerprint; skip
        // the cache for them so sibling changes never serve stale results.
        const isLooseScene = entry.fileAbs.toLowerCase().endsWith('.json')
        if (isLooseScene) mtimeMs = 0
        const key = entry.fileAbs + ':' + mtimeMs + ':' + size
        let probe = mtimeMs > 0 ? sceneProbeCache.get(key) : undefined
        if (!probe) {
          let hasVideo = false
          let hasSceneWebGL = false
          let compatibility: SceneProbe['compatibility'] = 'full'
          const unsupportedFeatures: string[] = []
          try {
            const pkgData = await readFile(entry.fileAbs)
            hasVideo = entry.fileAbs.toLowerCase().endsWith('.json')
              ? hasSceneVideoFromDir(dirname(entry.fileAbs))
              : hasSceneVideo(pkgData)
            {
              // Video-backed image layers can still belong to a full WebGL
              // composition (including author scripts that select one video by
              // local time). Probe the manifest even when a video TEX exists;
              // the scene player then owns the individual video layers.
              const manifest = entry.fileAbs.toLowerCase().endsWith('.json')
                ? buildSceneManifestFromDir(dirname(entry.fileAbs), 'check')
                : buildSceneManifest(pkgData, 'check', (() => { try { return JSON.parse(readFileSync(joinPath(entry.dir, 'project.json'), 'utf8')) as unknown } catch { return null } })())
              if (manifest?.scripted) {
                // Embedded scripts are ignored by the renderer, but the parsed
                // layers remain safe to replay. Report partial compatibility
                // without withholding water, particle and other supported passes.
                compatibility = 'partial'
                unsupportedFeatures.push('embedded-script')
              }
              hasSceneWebGL = Boolean(manifest && ((manifest.layers && manifest.layers.length >= 1) || (manifest.is3D && manifest.models && manifest.models.length > 0)))
            }
          } catch {
            // probe failure: capabilities stay negative
          }
          probe = { v: SCENE_PROBE_VERSION, hasVideo, hasSceneWebGL, compatibility, unsupportedFeatures }
          if (mtimeMs > 0) {
            // Bound the cache by evicting the oldest entries instead of
            // clearing everything at once: the whole-map clear would make a
            // library just above the cap re-probe on every open.
            sceneProbeCache.set(key, probe)
            while (sceneProbeCache.size > MAX_PROBE_CACHE) {
              const oldest = sceneProbeCache.keys().next().value
              if (oldest === undefined) break
              sceneProbeCache.delete(oldest)
            }
            persistProbes()
          }
        }
        const videoToken = probe.hasVideo && !probe.hasSceneWebGL ? tokenFor(entry.fileAbs) : null
        const sceneToken = probe.hasSceneWebGL ? tokenFor(entry.fileAbs) : null
        // Persist after issuing so freshly minted tokens survive a restart.
        persistTokens()
        writeJson(res, 200, {
          ok: true,
          videoUrl: videoToken !== null ? WE_API_PREFIX + '/scene-video/' + videoToken : null,
          sceneUrl: sceneToken !== null ? WE_API_PREFIX + '/scene-runtime/' + sceneToken : null,
          compatibility: probe.compatibility,
          unsupportedFeatures: probe.unsupportedFeatures,
        })
      } catch (error) {
        writeJson(res, 500, { ok: false, error: error instanceof Error ? error.message : String(error) })
      }
    },
  })

  // GET /shim.js — the WE API shim for web wallpaper iframes.
  routes.push({
    kind: 'exact',
    path: WE_API_PREFIX + '/shim.js',
    handler: (req, res) => {
      if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireContentOrigin(req, res)) return
      res.writeHead(200, {
        'content-type': 'text/javascript; charset=utf-8',
        'cache-control': 'no-store',
        'access-control-allow-origin': 'null',
      })
      res.end(WE_SHIM_JS)
    },
  })

  // GET /media/<token> and /preview/<token> — streamed files.
  for (const seg of ['media', 'preview']) {
    const prefix = WE_API_PREFIX + '/' + seg + '/'
    routes.push({
      kind: 'prefix',
      path: WE_API_PREFIX + '/' + seg,
      handler: (req, res) => {
        if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
        if (!requireSameOrigin(req, res)) return
        const abs = resolveToken(req, res, prefix)
        if (!abs) return
        // Convert WE .tex files to PNG for browser consumption
        if (abs.toLowerCase().endsWith('.tex')) {
          try {
            const texBuf = readFileSync(abs)
            const decoded = decodeTex(new Uint8Array(texBuf.buffer, texBuf.byteOffset, texBuf.byteLength))
            const pngBuf = encodePng(decoded.width, decoded.height, decoded.rgba)
            res.writeHead(200, { 'Content-Type': 'image/png', 'Content-Length': pngBuf.length, 'Cache-Control': 'public, max-age=86400' })
            res.end(pngBuf)
            return
          } catch { /* fall through to serveFile */ }
        }
        serveFile(abs, req, res, openReadStream)
      },
    })
  }

  /**
   * Convert one HEIC wallpaper into a <=2560px JPEG with the macOS-native
   * sips tool (no extra dependency). Darwin-only: Desktop Pictures scanning
   * only runs there, and the token map only ever holds scanned paths.
   */
  const defaultConvertImage = (src: string, dest: string): Promise<void> =>
    new Promise((resolvePromise, reject) => {
      if (process.platform !== 'darwin') {
        reject(new Error('heic conversion requires macOS'))
        return
      }
      execFile('/usr/bin/sips', ['-s', 'format', 'jpeg', '-s', 'formatOptions', '85', '-Z', '2560', src, '--out', dest], { timeout: 60000 }, (error) => {
        if (error !== null) reject(error)
        else resolvePromise()
      })
    })

  // GET /image/<token> — macOS Desktop Pictures: .jpg/.jpeg/.png/.webp are
  // served directly; HEIC/HEIF converts to JPEG, cached under
  // <store>/.cache/images keyed by path + mtime (stale keys pruned like the
  // scene caches). Anything else is rejected: only image formats leave here.
  const imagePrefix = WE_API_PREFIX + '/image/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/image',
    handler: (req, res) => {
      if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      const abs = resolveToken(req, res, imagePrefix)
      if (!abs) return
      if (/\.(jpe?g|png|webp)$/i.test(abs)) {
        serveFile(abs, req, res, openReadStream)
        return
      }
      if (!/\.hei[cf]$/i.test(abs)) { writeJson(res, 400, { ok: false, error: 'not-an-image' }); return }
      void (async () => {
        let mtime = 0
        try { mtime = statSync(abs).mtimeMs } catch { /* stays 0 */ }
        const cacheDir = joinPath(deps.storeDir, '.cache', 'images')
        const base = Buffer.from(abs, 'utf8').toString('base64url')
        const key = base + '_v1_' + String(Math.round(mtime)) + '.jpg'
        const cachePath = joinPath(cacheDir, key)
        if (!existsSync(cachePath)) {
          mkdirSync(cacheDir, { recursive: true })
          await (deps.convertImage ?? defaultConvertImage)(abs, cachePath)
          pruneStaleSceneCache(cacheDir, base, key)
        }
        serveFile(cachePath, req, res, openReadStream)
      })().catch((error: unknown) => {
        writeJson(res, 422, { ok: false, error: error instanceof Error ? error.message : String(error) })
      })
    },
  })

  // GET /scene-video/<token> — stream extracted MP4 video from scene pkg textures.
  const sceneVideoPrefix = WE_API_PREFIX + '/scene-video/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/scene-video',
    handler: (req, res) => {
      if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      const abs = resolveToken(req, res, sceneVideoPrefix)
      if (!abs) return
      void (async () => {
        let mtime = 0
        try { mtime = statSync(abs).mtimeMs } catch { /* stays 0 */ }
        const cacheDir = joinPath(deps.storeDir, '.cache', 'videos')
        const base = Buffer.from(abs, 'utf8').toString('base64url')
        const key = base + '_v' + String(SCENE_EXTRACTOR_VERSION) + '_' + String(Math.round(mtime)) + '.mp4'
        const cachePath = joinPath(cacheDir, key)
        if (!existsSync(cachePath)) {
          const { extractSceneVideo, extractSceneVideoFromDir } = await import('./pkg-extract.ts')
          const videoBytes = abs.toLowerCase().endsWith('.json')
            ? extractSceneVideoFromDir(dirname(abs))
            : extractSceneVideo(new Uint8Array(readFileSync(abs)))
          if (!videoBytes) {
            writeJson(res, 404, { ok: false, error: 'no-video-found' })
            return
          }
          mkdirSync(cacheDir, { recursive: true })
          writeFileSync(cachePath, videoBytes)
          pruneStaleSceneCache(cacheDir, base, key)
        }
        serveFile(cachePath, req, res, openReadStream)
      })().catch((error: unknown) => {
        writeJson(res, 422, { ok: false, error: error instanceof Error ? error.message : String(error) })
      })
    },
  })

  // GET /web/<token>/<subpath> — web-wallpaper project files. The token maps
  // to the entry HTML; subpaths resolve inside its directory only. HTML
  // responses carry the WE API shim ahead of the document.
  const webPrefix = WE_API_PREFIX + '/web/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/web',
    handler: (req, res) => {
      if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireContentOrigin(req, res)) return
      const pathname = new URL(req.url || '/', 'http://localhost').pathname
      let rest = ''
      try {
        rest = decodeURIComponent(pathname.slice(webPrefix.length))
      } catch { writeJson(res, 400, { ok: false, error: 'bad-request' }); return }
      const token = rest.split('/')[0] ?? ''
      const entryAbs = mediaMap.get(token)
      if (!entryAbs) { writeJson(res, 404, { ok: false, error: 'unknown-token' }); return }
      const root = dirname(entryAbs)
      const sub = rest.slice(token.length).replace(/^\/+/, '') || basename(entryAbs)
      const abs = resolvePath(root, sub)
      if (abs !== root && !abs.startsWith(root + sep)) {
        writeJson(res, 403, { ok: false, error: 'path-escape-rejected' })
        return
      }
      if (!existsSync(abs) || !statSync(abs).isFile()) { writeJson(res, 404, { ok: false, error: 'not-found' }); return }
      if (/\.html?$/i.test(abs)) {
        const html = readFileSync(abs, 'utf8')
        const defaultsTag = '<script>window.__dshWeDefaultProps = ' + JSON.stringify(webPropertyDefaults(root)).replace(/</g, '\\u003c') + ';</script>'
        const tag = defaultsTag + '<script src="' + WE_API_PREFIX + '/shim.js"></script>'
        const injected = /<head[^>]*>/i.test(html)
          ? html.replace(/<head[^>]*>/i, (m) => m + tag)
          : tag + html
        res.writeHead(200, {
          'content-type': 'text/html; charset=utf-8',
          'cache-control': 'no-store',
          // The sandboxed wallpaper frame loads its own project files with an
          // opaque origin, so module scripts and fetch() arrive as
          // cross-origin CORS requests with Origin: null.
          'access-control-allow-origin': 'null',
        })
        res.end(injected)
        return
      }
      serveFile(abs, req, res, openReadStream, { 'Access-Control-Allow-Origin': 'null' })
    },
  })

  // GET /scene-frame/<token> — decode the scene pkg's main texture to PNG,
  // cached under <store>/.cache/frames (keyed by path + extractor version +
  // mtime, #792: versionless keys served stale frames across upgrades).
  const framePrefix = WE_API_PREFIX + '/scene-frame/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/scene-frame',
    handler: (req, res) => {
      if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      const abs = resolveToken(req, res, framePrefix)
      if (!abs) return
      void (async () => {
        let mtime = 0
        try { mtime = statSync(abs).mtimeMs } catch { /* stays 0 */ }
        const cacheDir = joinPath(deps.storeDir, '.cache', 'frames')
        const base = Buffer.from(abs, 'utf8').toString('base64url')
        const key = base + '_v' + String(SCENE_EXTRACTOR_VERSION) + '_' + String(Math.round(mtime)) + '.png'
        const cachePath = joinPath(cacheDir, key)
        if (!existsSync(cachePath)) {
          const { extractSceneMainImage, extractSceneMainImageFromDir } = await import('./pkg-extract.ts')
          // A scene's main file is either the packed container (scene.pkg) or
          // a loose scene.json whose textures live alongside it in the
          // project directory (#521).
          const frame = abs.toLowerCase().endsWith('.json')
            ? extractSceneMainImageFromDir(dirname(abs))
            : extractSceneMainImage(new Uint8Array(readFileSync(abs)))
          mkdirSync(cacheDir, { recursive: true })
          writeFileSync(cachePath, frame.png)
          pruneStaleSceneCache(cacheDir, base, key)
        }
        res.setHeader('Content-Type', 'image/png')
        res.setHeader('Cache-Control', 'no-store')
        pipeFile(cachePath, res, openReadStream)
      })().catch((error: unknown) => {
        if (error instanceof TexUnsupportedError) {
          // Machine-readable signal for the client: the scene's textures use
          // a format this build cannot decode, so the frame route reports it
          // and the wallpaper controller falls back to the author preview
          // (#906).
          writeJson(res, 422, {
            ok: false,
            error: 'unsupported-tex-format',
            format: error.format,
            formatName: error.formatName,
            message: error.message,
          })
          return
        }
        writeJson(res, 422, { ok: false, error: error instanceof Error ? error.message : String(error) })
      })
    },
  })

  // GET /scene-runtime/<token> — serve the WebGL Scene Player HTML runtime.
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/scene-runtime',
    handler: (req, res) => {
      if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      res.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' })
      res.end(WE_SCENE_PLAYER_HTML)
    },
  })

  // GET /scene-manifest/<token> — return the JSON manifest of 2D layers and effects.
  const sceneManifestPrefix = WE_API_PREFIX + '/scene-manifest/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/scene-manifest',
    handler: (req, res) => {
      if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireContentOrigin(req, res)) return
      const abs = resolveToken(req, res, sceneManifestPrefix)
      if (!abs) return
      try {
        const token = Buffer.from(abs, 'utf8').toString('base64url')
        const manifest = abs.toLowerCase().endsWith('.json')
          ? buildSceneManifestFromDir(dirname(abs), token)
          : buildSceneManifest(new Uint8Array(readFileSync(abs)), token, (() => { try { return JSON.parse(readFileSync(joinPath(dirname(abs), 'project.json'), 'utf8')) as unknown } catch { return null } })())
        if (!manifest) {
          writeJson(res, 404, { ok: false, error: 'manifest-build-failed' })
          return
        }
        // The sandboxed scene player fetches the manifest with an opaque
        // origin (Origin: null), so the CORS response must allow exactly it.
        writeJson(res, 200, { ok: true, manifest }, { 'access-control-allow-origin': 'null' })
      } catch (err) {
        writeJson(res, 500, { ok: false, error: err instanceof Error ? err.message : String(err) })
      }
    },
  })

  // GET /scene-resource/<token>/<subpath> — serve decoded png or asset stream for scene player.
  const sceneResourcePrefix = WE_API_PREFIX + '/scene-resource/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/scene-resource',
    handler: (req, res) => {
      if (req.method !== 'GET') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireContentOrigin(req, res)) return
      const pathname = new URL(req.url || '/', 'http://localhost').pathname
      let rest = ''
      try {
        rest = decodeURIComponent(pathname.slice(sceneResourcePrefix.length))
      } catch { writeJson(res, 400, { ok: false, error: 'bad-request' }); return }
      const token = rest.split('/')[0] ?? ''
      const entryAbs = mediaMap.get(token)
      if (!entryAbs) { writeJson(res, 404, { ok: false, error: 'unknown-token' }); return }
      const subpath = rest.slice(token.length).replace(/^\/+/, '')
      if (!subpath) { writeJson(res, 400, { ok: false, error: 'missing-subpath' }); return }
      try {
        const resBytes = entryAbs.toLowerCase().endsWith('.json')
          ? extractSceneResourceFromDir(dirname(entryAbs), subpath)
          : extractSceneResource(new Uint8Array(readFileSync(entryAbs)), subpath)
        if (!resBytes) {
          writeJson(res, 404, { ok: false, error: 'resource-not-found' })
          return
        }
        // The extractor falls back to raw file bytes when a texture cannot
        // be decoded: label by payload, not by route name.
        const isPng = resBytes.length > 8 && resBytes[0] === 0x89 && resBytes[1] === 0x50 && resBytes[2] === 0x4e && resBytes[3] === 0x47
        const isMp4 = resBytes.length > 12 && resBytes[4] === 0x66 && resBytes[5] === 0x74 && resBytes[6] === 0x79 && resBytes[7] === 0x70
        // The sandboxed scene player textures load with crossOrigin, which
        // makes them CORS requests with Origin: null.
        res.writeHead(200, {
          'content-type': isPng ? 'image/png' : isMp4 ? 'video/mp4' : 'application/octet-stream',
          'cache-control': 'no-store',
          'access-control-allow-origin': 'null',
        })
        res.end(Buffer.from(resBytes))
      } catch (err) {
        writeJson(res, 500, { ok: false, error: err instanceof Error ? err.message : String(err) })
      }
    },
  })

  /** Read the {id} field of a wallpaper POST body. */
  const readId = (body: unknown): string => {
    if (typeof body !== 'object' || body === null) return ''
    const id = (body as Record<string, unknown>).id
    return typeof id === 'string' ? id : ''
  }

  /** Copy one library entry into the import store; dest must not exist. */
  const copyIntoStore = (entry: WallpaperEntry, dest: string): void => {
    mkdirSync(dest, { recursive: true })
    cpSync(entry.dir, joinPath(dest, 'project'), { recursive: true })
    const manifest = {
      sourceId: entry.id,
      title: entry.title,
      type: entry.type,
      srcMtime: entry.srcMtime,
      srcSize: entry.srcSize,
      importedAt: Date.now(),
      file: joinPath('project', entry.file),
      preview: entry.preview ? joinPath('project', entry.preview) : null,
    }
    writeFileSync(joinPath(dest, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8')
  }

  /** Register one JSON POST route with the standard error envelope. */
  const postJson = (path: string, run: (id: string, res: ServerResponse) => void): void => {
    routes.push({
      kind: 'exact',
      path,
      handler: (req, res) => {
        if (req.method !== 'POST') { writeJson(res, 405, { ok: false, error: 'method-not-allowed' }); return }
        if (!requireSameOrigin(req, res)) return
        readJsonBody(req).then((body) => {
          if (body === null) {
            writeJson(res, 400, { ok: false, error: 'invalid-body' })
            return
          }
          run(readId(body), res)
        }).catch((error: unknown) => {
          writeJson(res, 500, { ok: false, error: error instanceof Error ? error.message : String(error) })
        })
      },
    })
  }

  // POST /import — copy a library wallpaper project into the import store.
  postJson(WE_API_PREFIX + '/import', (id, res) => {
    if (id === '' || id.startsWith('imported/')) { writeJson(res, 400, { ok: false, error: 'bad-id' }); return }
    const entry = freshInventory().wallpapers.find((w) => w.id === id)
    if (!entry) { writeJson(res, 404, { ok: false, error: 'wallpaper-not-found' }); return }
    // macOS-managed entries (aerials / Desktop Pictures) are already local
    // and their dir is a shared system folder — never copy it wholesale.
    if (entry.source === 'system') { writeJson(res, 400, { ok: false, error: 'not-importable' }); return }
    const dest = joinPath(deps.storeDir, safeStoreId(id))
    if (existsSync(dest)) { writeJson(res, 409, { ok: false, error: 'already-imported' }); return }
    copyIntoStore(entry, dest)
    invalidateInventory()
    writeJson(res, 200, { ok: true, id: 'imported/' + entry.id })
  })

  // POST /reimport — refresh an imported copy from its (still present) source.
  postJson(WE_API_PREFIX + '/reimport', (id, res) => {
    if (!id.startsWith('imported/')) { writeJson(res, 400, { ok: false, error: 'bad-id' }); return }
    const sourceId = id.slice('imported/'.length)
    const dest = joinPath(deps.storeDir, safeStoreId(sourceId))
    if (!existsSync(dest)) { writeJson(res, 404, { ok: false, error: 'import-not-found' }); return }
    const source = freshInventory().wallpapers.find((w) => w.id === sourceId && w.source !== 'imported')
    if (!source) { writeJson(res, 410, { ok: false, error: 'source-gone' }); return }
    rmSync(dest, { recursive: true, force: true })
    copyIntoStore(source, dest)
    invalidateInventory()
    writeJson(res, 200, { ok: true, id })
  })

  // POST /remove — delete an imported copy (never touches the library).
  postJson(WE_API_PREFIX + '/remove', (id, res) => {
    if (!id.startsWith('imported/')) { writeJson(res, 400, { ok: false, error: 'bad-id' }); return }
    const dest = joinPath(deps.storeDir, safeStoreId(id.slice('imported/'.length)))
    if (!existsSync(dest)) { writeJson(res, 404, { ok: false, error: 'import-not-found' }); return }
    rmSync(dest, { recursive: true, force: true })
    invalidateInventory()
    writeJson(res, 200, { ok: true })
  })

  return routes
}
